# Generated by Django 3.2.11 on 2022-02-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=60)),
                ('vehicle_type', models.CharField(max_length=60)),
            ],
        ),
    ]
