# Generated by Django 3.2.11 on 2022-02-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='BdVehicle',
        ),
    ]
