# Generated by Django 3.2.11 on 2022-02-10 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehicle_bdvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdvehicle',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bdvehicle',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
