# Generated by Django 3.2.11 on 2022-02-11 07:31

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20220210_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bdvehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bdvehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='bdvehicle',
            name='image',
            field=models.ManyToManyField(related_name='BdVehicle', to='vehicle.Image'),
        ),
    ]
