# Generated by Django 3.2.11 on 2022-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20220211_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdvehicle',
            name='image',
            field=models.ManyToManyField(related_name='vehicles', to='vehicle.Image'),
        ),
    ]
